version: ""

formatter: markdown table

name: terraform-aws-datadog-integration-streaming

content: |-
  # terraform-aws-datadog-integration-streaming

  GitHub: [StratusGrid/terraform-aws-datadog-integration-streaming](https://github.com/StratusGrid/terraform-aws-datadog-integration-streaming)

  This module creates a DataDog integration meant to be used with CloudWatch metrics streams. For this reason, it disables DataDog service integrations which would be duplicated by a CloudWatch stream by default. The typical approach is to create one integration per account and one metrics stream per region (see example below).
  
  This is meant to be used with our module which creates the CloudWatch metrics stream and Firehose, which can be found here: [firehose-datadog-metrics-streaming](https://registry.terraform.io/modules/StratusGrid/firehose-datadog-metrics-streaming/aws/latest)

  ## Example

  Multi-region Example utilizing both the integration module to make the account level integration in DataDog and the metrics streaming module to create the Firehose and metrics stream in each region.
  ```hcl
  {{ include "examples/example-multi-region.tfnot" }}
  ```
  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  Note, manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml`

sections:
  show:
    - requirements
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
