version: ""

formatter: markdown table

name: terraform-aws-datadog-integration-streaming

content: |-
  # terraform-aws-datadog-integration-streaming

  GitHub: [StratusGrid/terraform-aws-datadog-integration-streaming](https://github.com/StratusGrid/terraform-aws-datadog-integration-streaming)

  ## Example

  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  Note, manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml`

sections:
  show:
    - requirements
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
